name:                homophone
version:             3.0.1.0
github:              "mdippery/homophone.hs"
license:             LGPL-3
author:              "Michael Dippery"
maintainer:          "michael@monkey-robot.com"
copyright:           "2019 Michael Dippery"

# extra-source-files:
# - README.md
# - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Utilities

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mdippery/homophone#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson >= 1.4.6.0
    - base64-bytestring >= 1.0.0.2
    - bytestring >= 0.10.8.2
    - directory >= 1.3.3.0
    - filepath >= 1.4.2.1
    - http-client >= 0.6.4
    - http-conduit >= 2.3.7.3
    - ini >= 0.4.1
    - network-uri >= 2.6.1.0
    - text >= 1.2.3.1

executables:
  homophone:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - homophone

tests:
  homophone-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - homophone
      - hspec
